### ISSUE TITLE
Paypal img in back office

### ISSUE THREAD

**Issue by nenes25** [SeyitDuman/sd_eicmslinks#5]
Hello,

With the way you load the paypal images in back office module configuration it doesn't work.
For example i test on a website with url http://www.prestashop.local/tests/1768/ 

![image](https://user-images.githubusercontent.com/7163132/106427721-22e8f180-6468-11eb-945f-a927b6594224.png)

Add base url before the image url fix the issue :
![image](https://user-images.githubusercontent.com/7163132/106427840-5461bd00-6468-11eb-8c16-0f92e49a789f.png)

**Comment by SeyitDuman** [comment]
Hello,

Thanks a lot for your reply.
I updated the code.

Regards,
