### ISSUE TITLE
Check php version

### ISSUE THREAD

**Issue by nenes25** [SeyitDuman/sd_eicmslinks#6]
Hello,
According to the devdocs https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart
Prestashop 1.7 is compatible from php 5.6 to php7.2 depending from the version.
As far as i know return types are allowed with php7.2 only : 
![image](https://user-images.githubusercontent.com/7163132/106428377-292b9d80-6469-11eb-93e5-4302ed399a4b.png)

So you need to check the php version, or to update the min prestashop version requirement :)

Regards,

**Comment by SeyitDuman** [comment]
Hello, 
Thanks a lot for your reply. 
I updated php requirements in README.md
Please see type hint in PHP function parameters and return values [here](https://mlocati.github.io/articles/php-type-hinting.html)
